#include "info.h"
#define NUM_HINTS 27

void printHints()
{
	//Header
	printf("\nSDL Hints\n");
	char *hints[NUM_HINTS] = {
		"SDL_ACCELEROMETER_AS_JOYSTICK",
		"SDL_FRAMEBUFFER_ACCELERATION",
		"SDL_GAMECONTROLLERCONFIG",
		"SDL_GRAB_KEYBOARD",
		"SDL_IDLE_TIMER_DISABLED",
		"SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS",
		"SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK",
		"SDL_MOUSE_RELATIVE_MODE_WARP",
		"SDL_ORIENTATIONS",
		"SDL_RENDER_DIRECT3D_THREADSAFE",
		"SDL_RENDER_DRIVER",
		"SDL_RENDER_OPENGL_SHADERS",
		"SDL_RENDER_SCALE_QUALITY",
		"SDL_RENDER_VSYNC",
		"SDL_TIMER_RESOLUTION",
		"SDL_VIDEO_ALLOW_SCREENSAVER",
		"SDL_VIDEO_HIGHDPI_DISABLED",
		"SDL_VIDEO_MAC_FULLSCREEN_SPACES",
		"SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS",
		"SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT",
		"SDL_VIDEO_WIN_D3DCOMPILER",
		"SDL_VIDEO_X11_XINERAMA",
		"SDL_VIDEO_X11_XRANDR",
		"SDL_VIDEO_X11_XVIDMODE",
		"SDL_WINDOWS_ENABLE_MESSAGELOOP",
		"SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN",
		"SDL_XINPUT_ENABLED"};
	for (int i = 0; i < NUM_HINTS; i++)
	{
		printf("\t%s : %s\n", hints[i], SDL_GetHint(hints[i]));
	}
}
